const SET_BOOKS = "SET_BOOKS";
const LOAD_BOOKS = "LOAD_BOOKS";
const SET_SELECTED_BOOK = "SET_SELECTED_BOOK";
const LOAD_SELECTED_BOOK = "LOAD_SELECTED_BOOK";
const LOAD_SEARCH_BOOKS = "LOAD_SEARCH_BOOKS";
const ADD_CART = "ADD_CART";
const ADD_COUNT_CART = "ADD_COUNT_CART";
const SUBTRACTION_COUNT_CART = "SUBTRACTION_COUNT_CART";
const DELETE_CART = "DELETE_CART";
const TOGGLE_FAVORITES = "TOGGLE_FAVORITES";
const SET_TOTAL = "SET_TOTAL";
const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";

export {
    SET_BOOKS,
    LOAD_BOOKS,
    LOAD_SELECTED_BOOK,
    SET_SELECTED_BOOK,
    LOAD_SEARCH_BOOKS,
    ADD_CART,
    ADD_COUNT_CART,
    SUBTRACTION_COUNT_CART,
    DELETE_CART,
    TOGGLE_FAVORITES,
    SET_TOTAL,
    SET_CURRENT_PAGE
}