const SET_BOOKS = "SET_BOOKS";
const LOAD_BOOKS = "LOAD_BOOKS";
const SET_SELECTED_BOOK = "SET_SELECTED_BOOK";
const LOAD_SELECTED_BOOK = "LOAD_SELECTED_BOOK";
const LOAD_SEARCH_BOOKS = "LOAD_SEARCH_BOOKS";

export {
    SET_BOOKS,
    LOAD_BOOKS,
    LOAD_SELECTED_BOOK,
    SET_SELECTED_BOOK,
    LOAD_SEARCH_BOOKS
}