const SIGN_UP_USER = "SIGN_UP_USER";
const SIGN_UP_ACTIVATE = "SIGN_UP_ACTIVATE";
const SIGN_IN_USER = "SIGN_IN_USER";
const GET_USER = "GET_USER";
const SET_USER = "SET_USER";
const UPDATE_USER_NAME = "UPDATE_USER_NAME";
const SET_USER_NAME = "SET_USER_NAME";
const LOG_OUT = "LOG_OUT";

export { 
    SIGN_UP_USER,
    SIGN_UP_ACTIVATE,
    SIGN_IN_USER,
    GET_USER,
    SET_USER,
    UPDATE_USER_NAME,
    SET_USER_NAME,
    LOG_OUT
 };